// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teacherinfo.DLL.Db_Context;

#nullable disable

namespace Teacherinfo.DLL.Migrations
{
    [DbContext(typeof(TeachterDbContext))]
    partial class TeachterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Teacherinfo.DLL.Models.TeacherTable", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Teacher_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("TeacherEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Teacher_Email");

                    b.Property<DateTime?>("TeacherHireDate")
                        .HasColumnType("datetime")
                        .HasColumnName("Teacher_Hire_Date");

                    b.Property<bool?>("TeacherIsActive")
                        .HasColumnType("bit")
                        .HasColumnName("Teacher_Is_Active");

                    b.Property<string>("TeacherName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Teacher_Name");

                    b.Property<string>("TeacherPhone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Teacher_Phone");

                    b.Property<string>("TeacherQualification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Teacher_Qualification");

                    b.HasKey("TeacherId")
                        .HasName("PK_Teacher");

                    b.ToTable("TeacherTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
